# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: df9e9f44aec000d698586026ac36b943ca6300b873443bb7ec280de246ee68c3c406212d0e118b7d13496a46eaa11fff758dae1a1453a3bc1fb0154c4f834318

test:
  secret_key_base: 2dbf2ebe4cf48eaf3b8ed9f68808d7ba7369a8b6c26ec0eb5710e25bc602dc37c184c40a5d0d760a2ca4240404a2d80dfb2efe1b29eb4b28db84c405cf45dd1b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
